# Generated by Django 2.2.2 on 2019-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('folio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('fecha_rescate', models.DateField()),
            ],
        ),
    ]
